## Co-Lab gives us option for using keras with GPU 

In [0]:
# https://keras.io/
!pip install -q keras
import keras

## Underlying os is Ubuntu 

### we can know by cat /etc/issue command

In [232]:
!cat /etc/issue

Ubuntu 17.10 \n \l



In [233]:
!ls

criminal_test.csv   precious.yaml	   submission_4.csv  submission.csv
criminal_train.csv  sample_submission.csv  submission_6.csv  why.csv
model.h5	    submission		   submission_7.csv
precious-kit.h5     submission_3.csv	   submission_8.csv


## currently clonig the full repository is working downloading the files 

In [6]:
!git clone https://github.com/papasanimohansrinivas/Data-Sets.git

Cloning into 'Data-Sets'...
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 15 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.


In [7]:
!ls

datalab  Data-Sets


In [8]:
cd Data-Sets

/content/Data-Sets


In [9]:
!ls

d17428d0-e-Criminal.rar  f2c2f440-8-dataset_he.zip  transformed_files.zip
d17428d0-e-Criminal.zip  README.md


In [10]:
!unzip d17428d0-e-Criminal.zip 

Archive:  d17428d0-e-Criminal.zip
   creating: d17428d0-e-Criminal/
  inflating: d17428d0-e-Criminal/criminal_test.csv  
  inflating: d17428d0-e-Criminal/criminal_train.csv  
  inflating: d17428d0-e-Criminal/sample_submission.csv  


In [11]:
cd d17428d0-e-Criminal	

/content/Data-Sets/d17428d0-e-Criminal


In [0]:
import pandas

In [0]:
from pandas import DataFrame

In [239]:
df=DataFrame.from_csv('./criminal_train.csv')

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.


In [240]:
df.columns

Index([u'IFATHER', u'NRCH17_2', u'IRHHSIZ2', u'IIHHSIZ2', u'IRKI17_2',
       u'IIKI17_2', u'IRHH65_2', u'IIHH65_2', u'PRXRETRY', u'PRXYDATA',
       u'MEDICARE', u'CAIDCHIP', u'CHAMPUS', u'PRVHLTIN', u'GRPHLTIN',
       u'HLTINNOS', u'HLCNOTYR', u'HLCNOTMO', u'HLCLAST', u'HLLOSRSN',
       u'HLNVCOST', u'HLNVOFFR', u'HLNVREF', u'HLNVNEED', u'HLNVSOR',
       u'IRMCDCHP', u'IIMCDCHP', u'IRMEDICR', u'IIMEDICR', u'IRCHMPUS',
       u'IICHMPUS', u'IRPRVHLT', u'IIPRVHLT', u'IROTHHLT', u'IIOTHHLT',
       u'HLCALLFG', u'HLCALL99', u'ANYHLTI2', u'IRINSUR4', u'IIINSUR4',
       u'OTHINS', u'CELLNOTCL', u'CELLWRKNG', u'IRFAMSOC', u'IIFAMSOC',
       u'IRFAMSSI', u'IIFAMSSI', u'IRFSTAMP', u'IIFSTAMP', u'IRFAMPMT',
       u'IIFAMPMT', u'IRFAMSVC', u'IIFAMSVC', u'IRWELMOS', u'IIWELMOS',
       u'IRPINC3', u'IRFAMIN3', u'IIPINC3', u'IIFAMIN3', u'GOVTPROG',
       u'POVERTY3', u'TOOLONG', u'TROUBUND', u'PDEN10', u'COUTYP2',
       u'MAIIN102', u'AIIND102', u'ANALWT_C', u'VESTR', u'VEREP', u'Crimina

In [0]:
from sklearn import preprocessing

targets = df['Criminal']

df=df.drop('Criminal',axis=1)



x = df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pandas.DataFrame(x_scaled)

In [243]:
df.shape[1:]


(70,)

In [0]:
from keras.models import Sequential

from keras.layers import Dense, Activation


In [0]:
model = Sequential()

In [0]:
model.add(Dense(100, input_dim=df.shape[1:][0],activation='relu'))

model.add(Dense(50,activation='tanh'))

model.add(Dense(20,activation='sigmoid'))

model.add(Dense(10,activation='softmax'))

model.add(Dense(5,activation='relu'))


model.add(Dense(2,activation='sigmoid'))

model.add(Dense(1,activation='sigmoid'))



In [0]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [306]:
model.fit(df,targets,epochs=10, batch_size=32)

Epoch 1/10
45718/45718 [==============================] - 11s 231us/step - loss: 0.2670 - acc: 0.9306
Epoch 2/10
45718/45718 [==============================] - 10s 219us/step - loss: 0.2523 - acc: 0.9306
Epoch 3/10
37408/45718 [=======================>......] - ETA: 1s - loss: 0.2413 - acc: 0.9301

45718/45718 [==============================] - 10s 220us/step - loss: 0.2286 - acc: 0.9306
Epoch 4/10
45718/45718 [==============================] - 10s 222us/step - loss: 0.1550 - acc: 0.9306
Epoch 5/10
45718/45718 [==============================] - 10s 225us/step - loss: 0.1440 - acc: 0.9306
Epoch 6/10
 3456/45718 [=>............................] - ETA: 9s - loss: 0.1286 - acc: 0.9424

45718/45718 [==============================] - 10s 225us/step - loss: 0.1373 - acc: 0.9306
Epoch 7/10
45718/45718 [==============================] - 10s 225us/step - loss: 0.1299 - acc: 0.9306
Epoch 8/10
41152/45718 [==========================>...] - ETA: 1s - loss: 0.1226 - acc: 0.9406

45718/45718 [==============================] - 10s 223us/step - loss: 0.1238 - acc: 0.9405
Epoch 9/10
45718/45718 [==============================] - 10s 224us/step - loss: 0.1199 - acc: 0.9466
Epoch 10/10
45718/45718 [==============================] - 10s 224us/step - loss: 0.1181 - acc: 0.9471


In [307]:
test=DataFrame.from_csv('./criminal_test.csv')

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.


In [308]:
test.head()

IFATHER  NRCH17_2  IRHHSIZ2  IIHHSIZ2  IRKI17_2  IIKI17_2  IRHH65_2  \
PERID                                                                           
66583679        4         0         4         1         2         1         1   
35494679        4         0         4         1         1         1         1   
79424679        2         0         3         1         2         1         1   
11744679        4         0         6         1         2         1         1   
31554679        1         0         4         1         3         1         1   

          IIHH65_2  PRXRETRY  PRXYDATA  ...    POVERTY3  TOOLONG  TROUBUND  \
PERID                                   ...                                  
66583679         1        99        99  ...           2        2         2   
35494679         1        99        99  ...           3        2         2   
79424679         1        99         1  ...           1        2         2   
11744679         1        99        99  ...           3        2         2   
31554679         1        99         1  ...           3        2         1   

          PDEN10  COUTYP2  MAIIN102  AIIND102      ANALWT_C  VESTR  VEREP  
PERID                                                                      
66583679       1        1         2         2  16346.795400  40020      1  
35494679       1        1         2         2   3008.863906  40044      2  
79424679       2        2         2         2    266.952503  40040      2  
11744679       1        1         2         2   5386.928199  40017      1  
31554679       1        1         2         2    173.489895  40017      1  

[5 rows x 70 columns]

In [0]:
x = test.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
test = pandas.DataFrame(x_scaled)

In [310]:
test.head()

0     1    2    3         4    5    6    7    8    9  ...     60  \
0  1.000000  0.25  0.6  0.0  0.333333  0.0  0.0  0.0  1.0  1.0 ...   0.75   
1  1.000000  0.25  0.6  0.0  0.000000  0.0  0.0  0.0  1.0  1.0 ...   1.00   
2  0.333333  0.25  0.4  0.0  0.333333  0.0  0.0  0.0  1.0  0.0 ...   0.50   
3  1.000000  0.25  1.0  0.0  0.333333  0.0  0.0  0.0  1.0  1.0 ...   1.00   
4  0.000000  0.25  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  0.0 ...   1.00   

         61        62   63   64   65   66        67        68   69  
0  0.010309  0.010309  0.0  0.0  1.0  1.0  0.204189  0.387755  0.0  
1  0.010309  0.010309  0.0  0.0  1.0  1.0  0.037542  0.877551  1.0  
2  0.010309  0.010309  0.5  0.5  1.0  1.0  0.003284  0.795918  1.0  
3  0.010309  0.010309  0.0  0.0  1.0  1.0  0.067254  0.326531  0.0  
4  0.010309  0.000000  0.0  0.0  1.0  1.0  0.002116  0.326531  0.0  

[5 rows x 70 columns]

In [332]:
y_pred=model.predict(test)

print

In [334]:
print(type(y_pred))

list(y_pred)

<type 'numpy.ndarray'>


[array([0.21075515], dtype=float32),
 array([0.00151669], dtype=float32),
 array([0.00151756], dtype=float32),
 array([0.00151282], dtype=float32),
 array([0.00159264], dtype=float32),
 array([0.00151569], dtype=float32),
 array([0.00192613], dtype=float32),
 array([0.19287597], dtype=float32),
 array([0.00160291], dtype=float32),
 array([0.00398822], dtype=float32),
 array([0.00196926], dtype=float32),
 array([0.00151921], dtype=float32),
 array([0.00151708], dtype=float32),
 array([0.00651305], dtype=float32),
 array([0.00151715], dtype=float32),
 array([0.00151389], dtype=float32),
 array([0.00151334], dtype=float32),
 array([0.04456612], dtype=float32),
 array([0.00151156], dtype=float32),
 array([0.00155117], dtype=float32),
 array([0.00151685], dtype=float32),
 array([0.10510764], dtype=float32),
 array([0.00151152], dtype=float32),
 array([0.00153308], dtype=float32),
 array([0.5904036], dtype=float32),
 array([0.06924086], dtype=float32),
 array([0.00158648], dtype=float32),
 a

In [0]:
y_pred = [1 if y[0]> 0.5 else 0 for y in y_pred]

In [0]:
ml=model.to_yaml()

In [0]:
with open('./precious.yaml','w') as g:
  g.write(ml)
g.close()

model.save("precious-kit-9.h5")

In [0]:
from google.colab import files

In [340]:
!ls

criminal_test.csv   precious-kit-9.h5	   submission_11.csv  submission_8.csv
criminal_train.csv  precious-kit.h5	   submission_12.csv  submission.csv
model.h5	    precious.yaml	   submission_3.csv   why.csv
precious-kit-2.h5   sample_submission.csv  submission_4.csv
precious-kit-6.h5   submission		   submission_6.csv
precious-kit-8.h5   submission_10.csv	   submission_7.csv


In [0]:
files.download('precious-kit-9.h5')

In [0]:
ids = []
import csv
with open('./criminal_test.csv') as dd:
  dd_= csv.reader(dd)
  
  for k in dd_:
    ids.append(k[0])
  

In [343]:
print(len(y_pred)==len(ids))
print(ids[0])
len(y_pred),len(ids)

False
PERID


(11430, 11431)

In [0]:
latest=DataFrame({'PERID':ids[1:],'Criminal':y_pred})

In [0]:
latest = latest[['PERID','Criminal']]

In [0]:
latest.to_csv('submission_13.csv', index=False)

In [347]:
!ls

criminal_test.csv   precious-kit-9.h5	   submission_11.csv  submission_7.csv
criminal_train.csv  precious-kit.h5	   submission_12.csv  submission_8.csv
model.h5	    precious.yaml	   submission_13.csv  submission.csv
precious-kit-2.h5   sample_submission.csv  submission_3.csv   why.csv
precious-kit-6.h5   submission		   submission_4.csv
precious-kit-8.h5   submission_10.csv	   submission_6.csv


In [0]:
from google.colab import files


files.download('submission_13.csv')

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
